/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestPageRouteImport } from './routes/test-page'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAccountRouteImport } from './routes/$locale/account'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleLocaleRouteImport } from './routes/$locale/_locale'

const TestPageRoute = TestPageRouteImport.update({
  id: '/test-page',
  path: '/test-page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAccountRoute = LocaleAccountRouteImport.update({
  id: '/$locale/account',
  path: '/$locale/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/$locale/about',
  path: '/$locale/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleLocaleRoute = LocaleLocaleRouteImport.update({
  id: '/$locale/_locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-page': typeof TestPageRoute
  '/$locale': typeof LocaleLocaleRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-page': typeof TestPageRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/account': typeof LocaleAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-page': typeof TestPageRoute
  '/$locale/_locale': typeof LocaleLocaleRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test-page'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/account'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-page' | '/$locale' | '/$locale/about' | '/$locale/account'
  id:
    | '__root__'
    | '/'
    | '/test-page'
    | '/$locale/_locale'
    | '/$locale/about'
    | '/$locale/account'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestPageRoute: typeof TestPageRoute
  LocaleLocaleRoute: typeof LocaleLocaleRoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleAccountRoute: typeof LocaleAccountRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-page': {
      id: '/test-page'
      path: '/test-page'
      fullPath: '/test-page'
      preLoaderRoute: typeof TestPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/account': {
      id: '/$locale/account'
      path: '/$locale/account'
      fullPath: '/$locale/account'
      preLoaderRoute: typeof LocaleAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/$locale/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_locale': {
      id: '/$locale/_locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleLocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestPageRoute: TestPageRoute,
  LocaleLocaleRoute: LocaleLocaleRoute,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleAccountRoute: LocaleAccountRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
